version: "3"

services:
  api:
    container_name: admintools-api
    user: root # avoids ton of volume mounting headaches in dev mode.
    build:
      context: .
    volumes:
      - ./:/opt/app
      # @see: http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html#the-node_modules-volume-trick
      - /opt/app/node_modules
    expose:
      - 3001
    ports:
      - 3001:3001
    env_file:
      - ./database.env
    networks:
      - majan
    environment: 
      - NODE_ENV=development
      - NODE_HOT_RELOAD=1
      - NODE_LOGGER_GRANULARLEVELS=1
      - NODE_CONFIG_DISABLE_FILE_WATCH="Y"
      - PORT=3001
    command: nodemon -L -e js server.js

  db:
    container_name: admintools-db
    image: mysql:5.7
    # port mapping not needed for the app, but convenient in debugging
    # to use some GUI tool (e.g. SequelPro) against the DB, on the host
    ports:
      - 5306:3306
    env_file:
      - ./database.env
    volumes:
      - majan_db_data:/var/lib/mysql
    restart: always
    networks:
      - majan

volumes:
  majan_db_data:

networks:
  majan:
    driver: bridge